/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SummaryCodeRouteImport } from './routes/summary/$code'
import { Route as LobbyCodeRouteImport } from './routes/lobby/$code'
import { Route as GameCodeRouteImport } from './routes/game/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryCodeRoute = SummaryCodeRouteImport.update({
  id: '/summary/$code',
  path: '/summary/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyCodeRoute = LobbyCodeRouteImport.update({
  id: '/lobby/$code',
  path: '/lobby/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCodeRoute = GameCodeRouteImport.update({
  id: '/game/$code',
  path: '/game/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$code': typeof GameCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/summary/$code': typeof SummaryCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$code': typeof GameCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/summary/$code': typeof SummaryCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$code': typeof GameCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/summary/$code': typeof SummaryCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/$code' | '/lobby/$code' | '/summary/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/$code' | '/lobby/$code' | '/summary/$code'
  id: '__root__' | '/' | '/game/$code' | '/lobby/$code' | '/summary/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameCodeRoute: typeof GameCodeRoute
  LobbyCodeRoute: typeof LobbyCodeRoute
  SummaryCodeRoute: typeof SummaryCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary/$code': {
      id: '/summary/$code'
      path: '/summary/$code'
      fullPath: '/summary/$code'
      preLoaderRoute: typeof SummaryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$code': {
      id: '/lobby/$code'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$code': {
      id: '/game/$code'
      path: '/game/$code'
      fullPath: '/game/$code'
      preLoaderRoute: typeof GameCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameCodeRoute: GameCodeRoute,
  LobbyCodeRoute: LobbyCodeRoute,
  SummaryCodeRoute: SummaryCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
