/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DailyLeaderboardRouteImport } from './routes/daily-leaderboard'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BattleRoyaleIndexRouteImport } from './routes/battle-royale/index'
import { Route as SummaryCodeRouteImport } from './routes/summary/$code'
import { Route as LobbyCodeRouteImport } from './routes/lobby/$code'
import { Route as GameCodeRouteImport } from './routes/game/$code'
import { Route as BattleRoyaleSoloRouteImport } from './routes/battle-royale/solo'
import { Route as BattleRoyaleMultiplayerRouteImport } from './routes/battle-royale/multiplayer'

const DailyLeaderboardRoute = DailyLeaderboardRouteImport.update({
  id: '/daily-leaderboard',
  path: '/daily-leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoyaleIndexRoute = BattleRoyaleIndexRouteImport.update({
  id: '/battle-royale/',
  path: '/battle-royale/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryCodeRoute = SummaryCodeRouteImport.update({
  id: '/summary/$code',
  path: '/summary/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyCodeRoute = LobbyCodeRouteImport.update({
  id: '/lobby/$code',
  path: '/lobby/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCodeRoute = GameCodeRouteImport.update({
  id: '/game/$code',
  path: '/game/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoyaleSoloRoute = BattleRoyaleSoloRouteImport.update({
  id: '/battle-royale/solo',
  path: '/battle-royale/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoyaleMultiplayerRoute = BattleRoyaleMultiplayerRouteImport.update({
  id: '/battle-royale/multiplayer',
  path: '/battle-royale/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/daily-leaderboard': typeof DailyLeaderboardRoute
  '/battle-royale/multiplayer': typeof BattleRoyaleMultiplayerRoute
  '/battle-royale/solo': typeof BattleRoyaleSoloRoute
  '/game/$code': typeof GameCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/summary/$code': typeof SummaryCodeRoute
  '/battle-royale': typeof BattleRoyaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/daily-leaderboard': typeof DailyLeaderboardRoute
  '/battle-royale/multiplayer': typeof BattleRoyaleMultiplayerRoute
  '/battle-royale/solo': typeof BattleRoyaleSoloRoute
  '/game/$code': typeof GameCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/summary/$code': typeof SummaryCodeRoute
  '/battle-royale': typeof BattleRoyaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/daily': typeof DailyRoute
  '/daily-leaderboard': typeof DailyLeaderboardRoute
  '/battle-royale/multiplayer': typeof BattleRoyaleMultiplayerRoute
  '/battle-royale/solo': typeof BattleRoyaleSoloRoute
  '/game/$code': typeof GameCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/summary/$code': typeof SummaryCodeRoute
  '/battle-royale/': typeof BattleRoyaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/daily'
    | '/daily-leaderboard'
    | '/battle-royale/multiplayer'
    | '/battle-royale/solo'
    | '/game/$code'
    | '/lobby/$code'
    | '/summary/$code'
    | '/battle-royale'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/daily'
    | '/daily-leaderboard'
    | '/battle-royale/multiplayer'
    | '/battle-royale/solo'
    | '/game/$code'
    | '/lobby/$code'
    | '/summary/$code'
    | '/battle-royale'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/daily'
    | '/daily-leaderboard'
    | '/battle-royale/multiplayer'
    | '/battle-royale/solo'
    | '/game/$code'
    | '/lobby/$code'
    | '/summary/$code'
    | '/battle-royale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DailyRoute: typeof DailyRoute
  DailyLeaderboardRoute: typeof DailyLeaderboardRoute
  BattleRoyaleMultiplayerRoute: typeof BattleRoyaleMultiplayerRoute
  BattleRoyaleSoloRoute: typeof BattleRoyaleSoloRoute
  GameCodeRoute: typeof GameCodeRoute
  LobbyCodeRoute: typeof LobbyCodeRoute
  SummaryCodeRoute: typeof SummaryCodeRoute
  BattleRoyaleIndexRoute: typeof BattleRoyaleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/daily-leaderboard': {
      id: '/daily-leaderboard'
      path: '/daily-leaderboard'
      fullPath: '/daily-leaderboard'
      preLoaderRoute: typeof DailyLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle-royale/': {
      id: '/battle-royale/'
      path: '/battle-royale'
      fullPath: '/battle-royale'
      preLoaderRoute: typeof BattleRoyaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary/$code': {
      id: '/summary/$code'
      path: '/summary/$code'
      fullPath: '/summary/$code'
      preLoaderRoute: typeof SummaryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$code': {
      id: '/lobby/$code'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$code': {
      id: '/game/$code'
      path: '/game/$code'
      fullPath: '/game/$code'
      preLoaderRoute: typeof GameCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle-royale/solo': {
      id: '/battle-royale/solo'
      path: '/battle-royale/solo'
      fullPath: '/battle-royale/solo'
      preLoaderRoute: typeof BattleRoyaleSoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle-royale/multiplayer': {
      id: '/battle-royale/multiplayer'
      path: '/battle-royale/multiplayer'
      fullPath: '/battle-royale/multiplayer'
      preLoaderRoute: typeof BattleRoyaleMultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DailyRoute: DailyRoute,
  DailyLeaderboardRoute: DailyLeaderboardRoute,
  BattleRoyaleMultiplayerRoute: BattleRoyaleMultiplayerRoute,
  BattleRoyaleSoloRoute: BattleRoyaleSoloRoute,
  GameCodeRoute: GameCodeRoute,
  LobbyCodeRoute: LobbyCodeRoute,
  SummaryCodeRoute: SummaryCodeRoute,
  BattleRoyaleIndexRoute: BattleRoyaleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
